### ISSUE TITLE
Not working properly with qUnit 1.19

### ISSUE THREAD

**Issue by ppritcha** [alawatthe/qunit-image#1]
This works correctly with qUnit 1.12, but when I changed to qUnit 1.19, the results of a failed test are not displayed.

**Comment by alawatthe** [comment]
Hi @ppritcha,

sorry it took me so long to get back to you. First of all, thank you for the interest in my library. I'm currently not using this library anymore (in fact I'm not using QUint anymore), so will not spend too much time getting it to work again. But I would accept a pull request.

However I have plans, to completely rewrite the library, to make it more generic, that it can work with QUint, Jasmine, Mocha, ... unfortunately I don't have time right now to do this :-/
